import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Create a sidebar for modules, using explicit categories and autogenerated content
  modulesSidebar: [
    {
      type: 'category',
      label: 'ROS 2 - The Robotic Nervous System',
      link: { type: 'doc', id: 'ros2/index' },
      items: [{type: 'autogenerated', dirName: 'ros2'}],
    },
    {
      type: 'category',
      label: 'Gazebo & Unity - The Digital Twin',
      link: { type: 'doc', id: 'gazebo-unity/index' },
      items: [{type: 'autogenerated', dirName: 'gazebo-unity'}],
    },
    {
      type: 'category',
      label: 'NVIDIA Isaac - The AI Robot Brain',
      link: { type: 'doc', id: 'nvidia-isaac/index' },
      items: [{type: 'autogenerated', dirName: 'nvidia-isaac'}],
    },
    {
      type: 'category',
      label: 'Vision-Language-Action - VLA',
      link: { type: 'doc', id: 'vla/index' },
      items: [{type: 'autogenerated', dirName: 'vla'}],
    },
  ],
};

export default sidebars;
