import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Create a sidebar for modules, using explicit categories and autogenerated content
  modulesSidebar: [
    {
      type: 'category',
      label: 'Module 1: ROS 2 - The Robotic Nervous System',
      link: { type: 'doc', id: 'ros2/index' },
      items: [
        'ros2/architecture',
        'ros2/nodes-topics-services-actions',
        'ros2/packages-workspace',
        'ros2/launch-parameters',
        'ros2/rclpy-basics',
        'ros2/pub-sub-examples',
        'ros2/urdf-overview',
        'ros2/simple-ros2-node',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Gazebo + Unity — The Digital Twin',
      link: { type: 'doc', id: 'modules/module2/digital-twins' },
      items: [
        'modules/module2/gazebo-intro',
        'modules/module2/creating-worlds',
        'modules/module2/spawning-robots',
        'modules/module2/gazebo-ros2-integration',
        'modules/module2/unity-robotics-overview',
        'modules/module2/unity-frontend',
        'modules/module2/simulation-example',
        'modules/module2/industry-usecases',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac — The AI Robot Brain',
      link: { type: 'doc', id: 'modules/module3/isaac-overview' },
      items: [
        'modules/module3/isaac-sim-basics',
        'modules/module3/isaac-ros',
        'modules/module3/gpu-robotics',
        'modules/module3/perception-pipelines',
        'modules/module3/fm-for-robotics',
        'modules/module3/rl-workflows',
        'modules/module3/isaac-humanoid-robotics',
        'modules/module3/example-navigation-or-perception',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action — The AI Embodiment',
      link: { type: 'doc', id: 'modules/module4/intro-to-vla' },
      items: [
        'modules/module4/evolution-of-vlm-to-vla',
        'modules/module4/perception-pipelines',
        'modules/module4/vla-models',
        'modules/module4/world-models-and-actions',
        'modules/module4/action-generation',
        'modules/module4/dataset-design',
        'modules/module4/training-pipelines',
        'modules/module4/humanoid-vla-example',
        'modules/module4/safety-and-failures',
      ],
    },
  ],
};

export default sidebars;
